# Generated by Django 6.0.5 on 2026-06-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('distance_unit', models.CharField(max_length=20)),
                ('fuel_volume_unit', models.CharField(max_length=20)),
                ('fuel_economy_unit', models.CharField(max_length=20)),
                ('fuel_types', models.JSONField(default=list)),
                ('subscription_plans', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
