# Generated by Django 6.0.5 on 2026-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_customersupport_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryconfig',
            name='ev_energy_unit',
            field=models.CharField(default='kWh/100KM', max_length=20),
        ),
    ]
