# Generated by Django 6.0.5 on 2026-06-12 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Efficiency multiplier (0.00 - 1.00)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ac_level', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'AC Factor',
                'verbose_name_plural': 'AC Factors',
                'ordering': ['ac_level'],
            },
        ),
        migrations.CreateModel(
            name='LoadFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Efficiency multiplier (0.00 - 1.00)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_percent', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Load Factor',
                'verbose_name_plural': 'Load Factors',
                'ordering': ['load_percent'],
            },
        ),
        migrations.CreateModel(
            name='PassengerFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Efficiency multiplier (0.00 - 1.00)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupants', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Passenger Factor',
                'verbose_name_plural': 'Passenger Factors',
                'ordering': ['occupants'],
            },
        ),
        migrations.CreateModel(
            name='TirePressureFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Efficiency multiplier (0.00 - 1.00)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pressure_percent', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Tire Pressure Factor',
                'verbose_name_plural': 'Tire Pressure Factors',
                'ordering': ['-pressure_percent'],
            },
        ),
        migrations.CreateModel(
            name='UseFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Efficiency multiplier (0.00 - 1.00)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odometer_km', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle Use Factor',
                'verbose_name_plural': 'Vehicle Use Factors',
                'ordering': ['odometer_km'],
            },
        ),
    ]
