# Generated by Django 6.0.5 on 2026-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='country_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
