# Generated by Django 6.0.5 on 2026-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='US', max_length=5),
        ),
    ]
