# Generated by Django 6.0.5 on 2026-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_trips_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='free_trips_used',
            field=models.IntegerField(default=0),
        ),
    ]
