# Generated by Django 6.0.5 on 2026-06-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_free_trips_limit_user_free_trips_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='free_trips_used',
            new_name='trips_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='free_trips_limit',
        ),
    ]
