# Generated by Django 6.0.5 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_free_trips_used_user_trips_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
