# Generated by Django 6.0.5 on 2026-06-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_current_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dial_code',
            field=models.CharField(default='+1', max_length=10),
        ),
    ]
