# Generated by Django 6.0.6 on 2026-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Equivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.CharField(help_text="Use {count} as placeholder. e.g. 'Equal to planting {count} trees'", max_length=500)),
                ('co2_kg_equivalent', models.FloatField(help_text='How many kg of CO2 this equivalent represents')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='co2_equivalents/')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CO2 Equivalent',
                'verbose_name_plural': 'CO2 Equivalents',
                'ordering': ['priority'],
            },
        ),
    ]
