# Generated by Django 6.0.6 on 2026-06-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada')], default='India', max_length=20)),
                ('state_name', models.CharField(blank=True, default='', max_length=64)),
                ('fuel_type', models.CharField(default='petrol', max_length=20)),
                ('fuel_price', models.FloatField(help_text='Price per litre/gallon/kWh, in local currency')),
                ('preferred_speed', models.FloatField(help_text="User's preferred driving speed (km/hr)")),
                ('mileage', models.FloatField(help_text='User-reported mileage (km/l or mpg) at preferred_speed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driving_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driving Profile',
                'verbose_name_plural': 'Driving Profiles',
            },
        ),
    ]
