# Generated by Django 6.0.5 on 2026-06-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileage_advisor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrivingProfile',
        ),
    ]
