# Generated by Django 6.0.5 on 2026-06-15 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cycle', models.BooleanField(default=False)),
                ('trip_type', models.CharField(choices=[('car', 'Car'), ('cycle', 'Cycle'), ('other', 'Other')], default='car', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('average_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co2_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_location', models.CharField(blank=True, default='', max_length=500)),
                ('destination', models.CharField(blank=True, default='', max_length=500)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_archieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=0.0)),
                ('time', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_data', to='tripanalytics.trip')),
            ],
            options={
                'verbose_name': 'Trip Data',
                'verbose_name_plural': 'Trip Data',
                'ordering': ['time'],
            },
        ),
    ]
